version: "3.9"

services:
  app:
    user: root
    restart: always
    build:
      dockerfile: build/app/Dockerfile
      context: .
    ports:
      - "8080:8080"
    volumes:
      - /var/lib/pcb/db/db.sqlite:/app/db/db.sqlite
    environment:
      - TOKEN=${TOKEN}
      - APP_ID=${APP_ID}
      - SERVER_ID=${SERVER_ID}
    command: [ "node", "/app/src/index.js" ]

  grafana:
    build:
      dockerfile: build/grafana/Dockerfile
      context: .
    ports:
      - "3000:3000"
    user: root
    volumes:
      - /var/lib/grafana:/var/lib/grafana
      - /var/lib/pcb/db/db.sqlite:/var/lib/discord/db.sqlite