version: "3.9"
services:
  app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    volumes:
      - /app/db:/var/lib/pcb/db
    environment:
      - TOKEN=${TOKEN}
      - APP_ID=${APP_ID}
      - SERVER_ID=${SERVER_ID}
    command: [ "node", "/app/src/index.js" ]
  grafana:
    image: grafana/grafana-enterprise:8.2.0
    ports:
      - 3000:3000
    user: root
    volumes:
      - ./grafana-storage:/var/lib/grafana
